[build]
  publish = "."
  functions = "netlify/functions"

# Endpoint amigable para la funci√≥n
[[redirects]]
  from = "/api/cotizar"
  to = "/.netlify/functions/sendQuote"
  status = 200
  force = true
